controller_list:
  - name: fake_test_1_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  - name: fake_gripper_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6