joints: {
  joint1: {id: 1, neutral: 205, max_angle: 90.0 , min_angle: -90, max_speed: 90},
  joint2: {id: 2, max_angle: 90.0 , min_angle: -90, max_speed: 90},
  joint3: {id: 3, max_angle: 90.0 , min_angle: -90, max_speed: 90},
  joint4: {id: 4, max_angle: 90.0 , min_angle: -90, max_speed: 90},
  joint5: {id: 5, max_angle: 90.0 , min_angle: -90, max_speed: 90},
  joint6: {id: 6, max_angle: 90.0 , min_angle: -90, max_speed: 90},
  joint7: {id: 7, max_angle: 90.0 , min_angle: -90, max_speed: 90},
}
controllers: {
  arm_controller: {type: follow_controller, joints: [joint1, joint2, joint3,
                                                    joint4, joint5, joint6, joint7], 
  action_name: learm_controller/follow_joint_trajectory, onboard: False }

# ArbotiBox 控制器配置